# ModderCam configuration
device: "/dev/video0"
host: "0.0.0.0"
http_port: 8090
ws_port: 8091
title: "ModderCam"

modes:
  - {width: 1280, height: 720, fps: 30, pixfmt: "MJPG"}
  - {width: 1920, height: 1080, fps: 30, pixfmt: "MJPG"}
  - {width: 1280, height: 720, fps: 30, pixfmt: "YUYV"}
  - {width: 640,  height: 480, fps: 30, pixfmt: "YUYV"}

bitrate_kbps: 3500
gop: 30
threads: 2
extra_ffmpeg: ""

webrtc:
  codec: "h264"
  bitrate_kbps: 3000
